version: "3.8"

services:
  users-service:
    build: ./users-service
    ports:
      - "5001:5001"

  products-service:
    build: ./products-service
    ports:
      - "5002:5002"

  orders-service:
    build: ./orders-service
    ports:
      - "5003:5003"
    depends_on:
      - users-service
      - products-service